#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
# Nginx should be listening on port 80
#++    at the root with a curl GET request.

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
sudo service nginx start